rest:
  host: "127.0.0.1"
  port: 8080
  cors_allowed_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"

models:
  - model: "gpt-4o-mini"
    model_provider: "openai"
    inference_provider:
      provider: "openai"
      model_name: "gpt-4"
    price:
      input_price: 0.00003
      output_price: 0.00006
    input_formats:
      - text
    output_formats:
      - text
    capabilities:
      - tools
    type: completions
    limits:
      max_context_size: 8000
    description: "GPT-4 is a large language model that can understand and generate human-like text"
  - model: "gpt-3.5-turbo"
    model_provider: "openai"
    inference_provider:
      provider: "openai"
      model_name: "gpt-3.5-turbo"
    price:
      input_price: 0.000002
      output_price: 0.000002
    input_formats:
      - text
    output_formats:
      - text
    capabilities:
      - tools
    type: completions
    limits:
      max_context_size: 4000
    description: "GPT-3.5 Turbo is a cost-effective language model for most chat and text generation tasks"
