version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
     - ./docker/clickhouse/server/config.d:/etc/clickhouse-server/config.d
    ports:
      - '8123:8123'
      - '9000:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    extra_hosts:
      - "host.docker.internal:host-gateway"